// Original 32px sticker art. Regenerate with node scripts/build-stickers.mjs.
export const builtinStickers = [
  {
    name: 'red heart',
    asset:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAi0lEQVR4nGNgGAWjYLCC/9/u/8eHKVVP0PJ9gRl4MbKhpKonyufEGIiMiVVPss8fdU5EwYQsoigkBpUDqGXhqAOGlgMYSMiG5FhMUllAd5/TKiTIKoqpGRJkW05pSFDkc2qEBNUsR3YE1SodShxBd59jcwQ2h9DU59gcQXefY3ME2U2uUTAKRsFgAgDLkfvs1KG9owAAAABJRU5ErkJggg==',
  },
  {
    name: 'pink heart',
    asset:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAjElEQVR4nGNgGAWjYLCC/9/u/8eHKVVP0PLrDRPxYmRDSVVPlM+JMRAZE6ueZJ+/33QABROyiKKQGFQOoJaFow4YWg5gICEbkmMxSWUB3X1Oq5AgqyimZkiQbTmlIUGRz6kRElSzHNkRVKt0KHEE3X2OzRHYHEJTn2NzBN19js0RZDe5RsEoGAWDCQAALUN9412Irg4AAAAASUVORK5CYII=',
  },
  {
    name: 'daisy',
    asset:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAoklEQVR4nO3Tuw2AMAxAQS9JwQbswBDMwySUVIwAbRCRoLBwEvxJCmzJDUK8U1AAfBgTjjW8bdN4NcQ/AbmoKYYbV0NUB0iDIlDJB7Z5iLsv07P3s2tFCAd8AVDrAPObIAUk45wTUQ3ieD92cZsDuBB2nAKUQAD9OjGCcxL4XfWTqAqAxG2gfpE6gELlwmbxUoBZHAPUryAHYB6kEM3iPlpzAtyF9bU5iGGAAAAAAElFTkSuQmCC',
  },
  {
    name: 'tulip',
    asset:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAqElEQVR4nGNgGAWjgAD4/+3+f2RMbfUEDdsXmIGC0S1Ax9jUU+yANwuWgTHMwOsNE7HiUQfQxQEgjMsB6JaPOmDUAVRzADoeOQ5gQCvbiXUAVesCch1AkcUwyyOrQ1HwoHEAIUwzB+DC+Kpnih1BjEOQLUJXTxVHkBoCVHUAA5bcQGzIUM0BuBxFTKjQxHJiHUAzy9EdQPXUT44DaG4hLkcMmOWjgFoAAPAhLlvj8nhlAAAAAElFTkSuQmCC',
  },
  {
    name: 'happy face',
    asset:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAmklEQVR4nGNgGAVDBfz/dv8/KZjqlr84WksSpqojRqYD0OOUHAeQnSbQLfxyexkck+oQskJkQB2AHOSUWootSsjyOTUcQFRI4HNApqc/GBOygJC6UQeQ5ABSDKa5AwYkEQ4qBwx4FIwMBzCgFcX4LMCF8VlMUn1ACwcQZTkhB9Ak9eOLigFpkFAjRIZ+m3BQOYBhoDsmo4CWAADT2cOP52R/8wAAAABJRU5ErkJggg==',
  },
  {
    name: 'angry face',
    asset:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAoklEQVR4nGNgGAVDBfz/dv8/KZjqlt+cXkcSpqojRqYD0OOUHAeQnSbQLfxyexkck+oQskIE2QGZnv4omJBFuNQT7QDkIAf5GN1AXA4hpI6oqMAV9NgswuUAiqICnwNIjYJRB1DFAeTEMc0cQC086oBRBxBVGhKTG4gtopEtJqk+oIUDiLKcVlFBVptgwBok1AiRod8mHFQOYBjojskooCUAAIc8WYcXW0wQAAAAAElFTkSuQmCC',
  },
  {
    name: 'sad face',
    asset:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAqElEQVR4nGNgGAVDBfz/dv8/KZjqlr84WksSpqojRqYD0OOUHAeQnSbQLfxyexkck+oQskJkQB2AHOSUWootSsjyOTUcQFRI4HNApqc/GBOygJC6UQeQ5ABSDKa5AwYkEVKC69bvBeNRB1DdAbBEhgvD1C06fQGMSXIAA1pRTE0HkFQrYnMApdmQotqQ7g5gGOgGCTEhQowDKLJ01AHYHDFgHZNRQEsAAKO7xv/9vay9AAAAAElFTkSuQmCC',
  },
  {
    name: 'blushing face',
    asset:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAApklEQVR4nGNgGAVDBfz/dv8/KZjqlr84WksSpqojRqYD0OOUHAeQnSbQLfxyexkck+oQskJkQB2AHOSUWootSsjyOTUcQFRI4HNApqc/GBOygJC6UQeQ5ABSDKa5A+ieCK83TMTAxFqCTy9FDiA2CoaHAwYkETKgFcX4LMCF8VlMUn1ACwcQZTkhB9Ak++GLigFpkFAjRIZ+m3BQOYBhoDsmo4CWAACW28B3hD7tEgAAAABJRU5ErkJggg==',
  },
  {
    name: 'sparkles',
    asset:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAmklEQVR4nO2WXQrAIAiAPe6uuNPsaVfYa6MHYYRDLX+2SJCIRD/txwCWBEm5jpLmtNqd+1ZMITRO0wDq2tMORxMQDgDXUam5KwBkV6DXVhS4zYzLygxgZF9Ny+52sNpglHIAlA5n+qYau39VQFoZ1zPwSQDofAfcQMKyTgHgHLsCSDvdfADa/j3XIwPePxgtyNx3XAqRFnxJpNyTyeqwf1Jp8QAAAABJRU5ErkJggg==',
  },
  {
    name: 'little bow',
    asset:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAArElEQVR4nGNgGAWjYBQMNvD/2/3/yJiu5oEU7AvMQMGUOIJk82AaXi1YD8YwDcT6AptabOaR5IDrDRMxMDZDQGLY1NLMAdgw3RyAHq8wTFcHvFm6DgWPOmB4OYCYhEWKA0guiIaEA0jJhhQ5ALlIxSZOSJ6mDqBUH05HoFc85DoAl3kkA0ocQDGgNAoothxXiifkAKqExKB0AK6gJTvVE+MIUlIxtRu1o4DmAACYfTxuT1TcxgAAAABJRU5ErkJggg==',
  },
] as const;
